name: 🔨📂 Build & Deploy to PROD

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js from package.json
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"

      - name: Install dependencies
        run: pnpm ci

      - name: 🔨 Build Project
        run: pnpm run build

      - id: deployProd
        name: 📂 Sync files to prod folder
        continue-on-error: true
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{secrets.password}}
          localDir: "./dist/"
          remoteDir: "./"
          port: 22

      - name: 🔁 Retry PROD upload if handshake failed
        if: steps.deployProd.outcome == 'failure'
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{secrets.password}}
          localDir: "./dist/"
          remoteDir: "./"
          port: 22
